#!/bin/bash
# Report on Elementor 4.2.0 Official Interfaces

echo ""
echo "========================================================================"
echo "ELEMENTOR 4.2.0 INSTALLED INTERFACES REPORT"
echo "========================================================================"
echo ""

ELEMENTOR_PATH="/workspaces/tshirtswiss/wordpress-project/plugins/elementor"
IMPORT_EXPORT_PATH="$ELEMENTOR_PATH/app/modules/import-export"

echo "1. WP-CLI COMMAND INTERFACE"
echo "------------------------------------------------------------------------"
echo ""
echo "File: app/modules/import-export/wp-cli.php"
echo ""
echo "Registered Commands:"
echo "  - wp elementor kit export"
echo "  - wp elementor kit import"
echo "  - wp elementor kit revert"
echo ""
echo "Export Signature:"
echo "  wp elementor kit export <output-path> [--include=content,site-settings,templates]"
echo ""
echo "Import Signature:"
echo "  wp elementor kit import <input-path> [--include=...] [--sourceType=local|remote|library]"
echo ""
echo "Authorization:"
echo "  - Requires: current_user_can('manage_options')"
echo "  - Error: 'You must run this command as an admin user'"
echo ""
echo "Implementation:"
echo "  1. Calls: Plugin::instance()->app->get_component('import-export')"
echo "  2. Calls: import_export_module->export_kit() or import_export_module->import_kit()"
echo ""

echo "2. OFFICIAL MODULE API"
echo "------------------------------------------------------------------------"
echo ""
echo "Class: Elementor\\App\\Modules\\ImportExport\\Module"
echo "File: app/modules/import-export/module.php"
echo ""
echo "Public Methods:"
echo "  - export_kit(array \$settings): array"
echo "  - import_kit(string \$path, array \$settings, bool \$split_to_chunks = false): array"
echo "  - import_kit_by_runner(string \$session_id, string \$runner_name): array"
echo "  - revert_last_imported_kit(): void"
echo ""
echo "These methods handle the actual import/export logic."
echo ""

echo "3. IMPORT/EXPORT PROCESS CLASSES"
echo "------------------------------------------------------------------------"
echo ""
echo "Export Process:"
echo "  Class: Elementor\\App\\Modules\\ImportExport\\Processes\\Export"
echo "  Usage: new Export(array \$settings)"
echo ""
echo "Import Process:"
echo "  Class: Elementor\\App\\Modules\\ImportExport\\Processes\\Import"
echo "  Usage: new Import(string \$path, array \$settings)"
echo ""

echo "4. FILE STRUCTURE"
echo "------------------------------------------------------------------------"
echo ""
find "$IMPORT_EXPORT_PATH" -type f -name "*.php" | sort | sed 's|'"$IMPORT_EXPORT_PATH"'||' | sed 's|^/||' | awk '{print "  - " $0}'
echo ""

echo "5. OFFICIAL INTERFACE RECOMMENDATION"
echo "------------------------------------------------------------------------"
echo ""
echo "✓ PRIMARY: Use WP-CLI commands"
echo "  - wp elementor kit export /path/to/kit.zip"
echo "  - wp elementor kit import /path/to/kit.zip"
echo "  - Officially supported and documented"
echo "  - Used by Elementor UI and developers"
echo ""
echo "✓ SECONDARY: Use Module::import_kit() method directly"
echo "  - Requires: Elementor plugin loaded"
echo "  - Requires: Admin user context (current_user_can('manage_options'))"
echo "  - Called internally by WP-CLI"
echo "  - Best for: Programmatic imports in custom plugins"
echo ""
echo "✗ AVOID: Instantiating Import/Export classes directly"
echo "  - Requires internal knowledge of process flow"
echo "  - Doesn't provide the same validation/setup as Module methods"
echo ""

echo "6. KNOWN ISSUES & SOLUTIONS"
echo "------------------------------------------------------------------------"
echo ""
echo "Issue: WP-CLI 'You must run this command as an admin user'"
echo "Cause: WP-CLI running as root without WordPress user context"
echo "Solution: Use Module::import_kit() in eval-file context instead"
echo "          The eval-file runs in WordPress context and can set user"
echo ""

echo "========================================================================"
echo "END OF REPORT"
echo "========================================================================"
echo ""
